import { afterEach, describe, expect, it } from 'vitest'
import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { MemoryService } from '../src/service.ts'
import { Context } from '@deepseek-ai/cordis'
import type { TemporaryMemoryHome } from './helpers.ts'
import { draft, proposer, reviewer, temporaryMemoryHome } from './helpers.ts'

let home: TemporaryMemoryHome | undefined
let ctx: Context | undefined

afterEach(async () => {
  await ctx?.fiber.dispose()
  home?.cleanup()
  ctx = undefined
  home = undefined
})

describe('MarkdownProjection', () => {
  it('renders the same canonical fields for humans and escapes active Markdown/HTML', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)
    const candidate = service.propose({
      content: draft({
        subject: '# Hidden heading [link](bad)',
        action: '<script>alert(1)</script>\n```spoof```',
      }),
      actor: proposer,
      now: 1_000,
    })
    service.review(candidate.id, {
      action: 'publish', actor: reviewer, reason: 'Escaping fixture reviewed.', now: 2_000,
    })
    const record = service.listRecords()[0]!
    const path = join(home.config.projectionPath, 'records', `${record.memoryId}.md`)
    const page = readFileSync(path, 'utf8')
    expect(page).toContain('## When')
    expect(page).toContain('## What')
    expect(page).toContain('&lt;script&gt;')
    expect(page).not.toContain('<script>')
    expect(page).toContain('Generated by dsh-memory')
    expect(readFileSync(join(home.config.projectionPath, 'README.md'), 'utf8')).toContain(record.memoryId)
  })

  it('rebuilds byte-identically and removes only manifest-owned stale pages', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)
    const candidate = service.propose({ content: draft(), actor: proposer, now: 1_000 })
    service.review(candidate.id, { action: 'publish', actor: reviewer, reason: 'Verified.', now: 2_000 })
    const before = new Map(readdirSync(home.config.projectionPath, { recursive: true })
      .map(item => String(item))
      .filter(item => item.endsWith('.md'))
      .map(item => [item, readFileSync(join(home!.config.projectionPath, item), 'utf8')]))
    service.projection.rebuild(service.store)
    const after = new Map(readdirSync(home.config.projectionPath, { recursive: true })
      .map(item => String(item))
      .filter(item => item.endsWith('.md'))
      .map(item => [item, readFileSync(join(home!.config.projectionPath, item), 'utf8')]))
    expect(after).toEqual(before)
  })

  it('keeps committed canonical mutations usable when the human projection is degraded', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    mkdirSync(dirname(home.config.projectionPath), { recursive: true })
    writeFileSync(home.config.projectionPath, 'blocks projection directory')
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)

    expect(service.health.projectionState).toBe('degraded')
    const candidate = service.propose({ content: draft(), actor: proposer, now: 1_000 })
    service.review(candidate.id, { action: 'publish', actor: reviewer, reason: 'Verified.', now: 2_000 })
    expect(service.listRecords()).toHaveLength(1)
    expect(service.health.lastProjectionError).toContain('stage=review')

    unlinkSync(home.config.projectionPath)
    service.rebuild()
    expect(service.health.projectionState).toBe('ready')
    expect(service.health.lastProjectionError).toBeUndefined()
    expect(readFileSync(join(home.config.projectionPath, 'README.md'), 'utf8')).toContain('Active: 1')
  })
})
