import { afterEach, describe, expect, it } from 'vitest'
import { existsSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { MemoryService } from '../src/service.ts'
import { Context } from '@deepseek-ai/cordis'
import type { TemporaryMemoryHome } from './helpers.ts'
import { draft, proposer, reviewer, temporaryMemoryHome } from './helpers.ts'

let home: TemporaryMemoryHome | undefined
let ctx: Context | undefined

afterEach(async () => {
  await ctx?.fiber.dispose()
  home?.cleanup()
  ctx = undefined
  home = undefined
})

describe('MarkdownProjection', () => {
  it('renders the same canonical fields for humans and escapes active Markdown/HTML', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)
    const candidate = service.propose({
      content: draft({
        subject: '# Hidden heading [link](bad)',
        action: '<script>alert(1)</script>\n```spoof```',
      }),
      actor: proposer,
      now: 1_000,
    })
    service.review(candidate.id, {
      action: 'publish', actor: reviewer, reason: 'Escaping fixture reviewed.', now: 2_000,
    })
    const record = service.listRecords()[0]!
    const path = join(home.config.projectionPath, 'records', `${record.memoryId}.md`)
    const page = readFileSync(path, 'utf8')
    expect(page).toContain('## When')
    expect(page).toContain('## What')
    expect(page).toContain('&lt;script&gt;')
    expect(page).not.toContain('<script>')
    expect(page).toContain('Generated by dsh-memory')
    const index = readFileSync(join(home.config.projectionPath, 'README.md'), 'utf8')
    expect(index).toContain(record.memoryId)
    expect(index).toContain('## By scope')
    expect(index).toContain('## By kind')
    expect(index).toContain('## By status')
    expect(index).toContain('## By owner')
    expect(index).toContain('## Freshness')
    expect(readFileSync(join(home.config.projectionPath, 'review', 'expiring.md'), 'utf8')).toContain('Maintenance review queue')
  })

  it('rebuilds byte-identically and removes only manifest-owned stale pages', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)
    const candidate = service.propose({ content: draft(), actor: proposer, now: 1_000 })
    service.review(candidate.id, { action: 'publish', actor: reviewer, reason: 'Verified.', now: 2_000 })
    service.projection.rebuild(service.store, 10_000)
    const before = new Map(readdirSync(home.config.projectionPath, { recursive: true })
      .map(item => String(item))
      .filter(item => item.endsWith('.md'))
      .map(item => [item, readFileSync(join(home!.config.projectionPath, item), 'utf8')]))
    service.projection.rebuild(service.store, 10_000)
    const after = new Map(readdirSync(home.config.projectionPath, { recursive: true })
      .map(item => String(item))
      .filter(item => item.endsWith('.md'))
      .map(item => [item, readFileSync(join(home!.config.projectionPath, item), 'utf8')]))
    expect(after).toEqual(before)
    assertProjectionLinks(home.config.projectionPath, [...after.keys()])
    const verification = service.projection.verify()
    expect(verification).toMatchObject({ valid: true, fileCount: after.size })
    expect(verification.generation).toMatch(/^[a-f0-9]{64}$/)

    const recordRelative = `records/${service.listRecords()[0]!.memoryId}.md`
    writeFileSync(join(home.config.projectionPath, 'records', `${service.listRecords()[0]!.memoryId}.md`), 'manually changed')
    expect(service.projection.verify()).toMatchObject({
      valid: false,
      errors: [`projection content hash mismatch: ${recordRelative}`],
    })
    service.projection.rebuild(service.store, 10_000)
    expect(service.projection.verify().valid).toBe(true)
  })

  it('keeps committed canonical mutations usable when the human projection is degraded', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    mkdirSync(dirname(home.config.projectionPath), { recursive: true })
    writeFileSync(home.config.projectionPath, 'blocks projection directory')
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)

    expect(service.health.projectionState).toBe('degraded')
    const candidate = service.propose({ content: draft(), actor: proposer, now: 1_000 })
    service.review(candidate.id, { action: 'publish', actor: reviewer, reason: 'Verified.', now: 2_000 })
    expect(service.listRecords()).toHaveLength(1)
    expect(service.health.lastProjectionError).toContain('stage=review')

    unlinkSync(home.config.projectionPath)
    service.rebuild()
    expect(service.health.projectionState).toBe('ready')
    expect(service.health.lastProjectionError).toBeUndefined()
    expect(readFileSync(join(home.config.projectionPath, 'README.md'), 'utf8')).toContain('Active: 1')
  })

  it('removes manifest-owned deleted pages without touching human files', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)
    const candidate = service.propose({ content: draft(), actor: proposer, now: 1_000 })
    service.review(candidate.id, { action: 'publish', actor: reviewer, reason: 'Verified.', now: 2_000 })
    const record = service.listRecords()[0]!
    const recordPath = join(home.config.projectionPath, 'records', `${record.memoryId}.md`)
    const humanPath = join(home.config.projectionPath, 'notes.md')
    writeFileSync(humanPath, 'human-owned note')
    expect(existsSync(recordPath)).toBe(true)

    service.transition(record.memoryId, {
      action: 'delete', expectedRevision: record.revision,
      actor: reviewer, reason: 'Approved deletion.', now: 3_000,
    })
    expect(existsSync(recordPath)).toBe(false)
    expect(readFileSync(humanPath, 'utf8')).toBe('human-owned note')
    expect(service.projection.verify().valid).toBe(true)
  })

  it('cleans managed stale pages even when the generation manifest is lost', () => {
    home = temporaryMemoryHome({ markdownProjection: true })
    ctx = new Context()
    const service = new MemoryService(ctx, home.config)
    const candidate = service.propose({ content: draft(), actor: proposer, now: 1_000 })
    service.review(candidate.id, { action: 'publish', actor: reviewer, reason: 'Verified.', now: 2_000 })
    const record = service.listRecords()[0]!
    const recordPath = join(home.config.projectionPath, 'records', `${record.memoryId}.md`)
    const humanPath = join(home.config.projectionPath, 'notes.md')
    writeFileSync(humanPath, 'human-owned note')
    unlinkSync(join(home.config.projectionPath, '.dsh-memory-manifest.json'))

    service.transition(record.memoryId, {
      action: 'delete', expectedRevision: record.revision,
      actor: reviewer, reason: 'Approved deletion.', now: 3_000,
    })

    expect(existsSync(recordPath)).toBe(false)
    expect(readFileSync(humanPath, 'utf8')).toBe('human-owned note')
    expect(service.projection.verify().valid).toBe(true)
  })
})

function assertProjectionLinks(root: string, pages: readonly string[]): void {
  for (const page of pages) {
    const path = join(root, page)
    const content = readFileSync(path, 'utf8')
    for (const match of content.matchAll(/\]\(([^)]+\.md)\)/g)) {
      const target = match[1]
      if (target === undefined) continue
      expect(existsSync(resolve(dirname(path), target)), `${page} links to ${target}`).toBe(true)
    }
  }
}
