import { randomUUID } from 'node:crypto'
import {
  closeSync,
  existsSync,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { basename, dirname, join } from 'node:path'
import type { ResolvedConfig } from './config.ts'
import type { MemoryStore } from './store.ts'
import type { MemoryCandidate, MemoryConflict, MemoryRecord, MemoryRevision } from './types.ts'

const MANIFEST = '.dsh-memory-manifest.json'

/** Rebuildable Markdown view for humans. Canonical state always remains in SQLite. */
export class MarkdownProjection {
  readonly path: string

  constructor(private readonly config: ResolvedConfig) {
    this.path = config.projectionPath
  }

  rebuild(store: MemoryStore): void {
    if (!this.config.markdownProjection || this.config.readOnly) return
    mkdirSync(this.path, { recursive: true, mode: 0o700 })
    mkdirSync(join(this.path, 'records'), { recursive: true, mode: 0o700 })
    mkdirSync(join(this.path, 'review'), { recursive: true, mode: 0o700 })

    const records = store.listRecords(['active', 'conflicted', 'stale', 'archived'])
    const candidates = store.listCandidates('candidate')
    const conflicts = store.listConflicts('open')
    const revisions = new Map<string, readonly MemoryRevision[]>()
    for (const record of records) revisions.set(record.memoryId, store.listRevisions(record.memoryId))

    const generated = new Set<string>()
    for (const record of records) {
      const relative = `records/${safeFileName(record.memoryId)}.md`
      atomicWrite(join(this.path, relative), renderRecord(record, revisions.get(record.memoryId) ?? []))
      generated.add(relative)
    }
    atomicWrite(join(this.path, 'README.md'), renderIndex(records, candidates, conflicts))
    generated.add('README.md')
    atomicWrite(join(this.path, 'review', 'candidates.md'), renderCandidates(candidates))
    generated.add('review/candidates.md')
    atomicWrite(join(this.path, 'review', 'conflicts.md'), renderConflicts(conflicts, records))
    generated.add('review/conflicts.md')

    const old = readManifest(this.path)
    for (const relative of old) {
      if (generated.has(relative)) continue
      removeGeneratedFile(this.path, relative)
    }
    atomicWrite(join(this.path, MANIFEST), `${JSON.stringify([...generated].sort(), null, 2)}\n`)
  }
}

function renderIndex(
  records: readonly MemoryRecord[],
  candidates: readonly MemoryCandidate[],
  conflicts: readonly MemoryConflict[],
): string {
  const grouped = new Map<string, MemoryRecord[]>()
  for (const record of records) {
    const key = `${record.scope.type}:${record.scope.key}`
    const group = grouped.get(key) ?? []
    group.push(record)
    grouped.set(key, group)
  }
  const lines = [
    '# Team knowledge',
    '',
    '> Generated by dsh-memory from the canonical store. Do not edit this projection.',
    '',
    `- Active: ${records.filter(record => record.status === 'active').length}`,
    `- Stale: ${records.filter(record => record.status === 'stale').length}`,
    `- Archived: ${records.filter(record => record.status === 'archived').length}`,
    `- Conflicted records: ${records.filter(record => record.status === 'conflicted').length}`,
    `- Review candidates: [${candidates.length}](review/candidates.md)`,
    `- Open conflicts: [${conflicts.length}](review/conflicts.md)`,
    '',
  ]
  for (const [scope, group] of [...grouped].sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`## ${escapeInline(scope)}`, '')
    for (const record of group.sort((left, right) => left.subject.localeCompare(right.subject))) {
      lines.push(`- [${escapeInline(record.subject)}](records/${safeFileName(record.memoryId)}.md) · ${record.kind} · ${record.status} · r${record.revision}`)
    }
    lines.push('')
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderRecord(record: MemoryRecord, revisions: readonly MemoryRevision[]): string {
  const lines = [
    `# ${escapeInline(record.subject)}`,
    '',
    '> Generated by dsh-memory. Review decisions must use the service or an approved command.',
    '',
    '## Identity',
    '',
    `- ID: \`${escapeCode(record.memoryId)}\``,
    `- Revision: ${record.revision}`,
    `- Status: ${record.status}`,
    `- Kind: ${record.kind}`,
    `- Scope: ${escapeInline(record.scope.type)} · \`${escapeCode(record.scope.key)}\``,
    `- Sensitivity: ${record.sensitivity}`,
    `- Confidence: ${record.confidence.toFixed(2)}`,
    `- Owner: ${escapeInline(record.owner)}`,
    `- Created: ${formatTime(record.createdAt)}`,
    `- Updated: ${formatTime(record.updatedAt)}`,
    ...(record.expiresAt === undefined ? [] : [`- Expires: ${formatTime(record.expiresAt)}`]),
    '',
    '## When',
    '',
    htmlPre(record.applicability),
    '',
    '## What',
    '',
    htmlPre(record.action),
    '',
    '## Why',
    '',
    htmlPre(record.rationale),
    '',
    '## Evidence',
    '',
  ]
  if (record.evidence.length === 0) lines.push('- No evidence loaded.')
  else for (const evidence of record.evidence) {
    lines.push(`- **${evidence.kind}** · \`${escapeCode(evidence.locator)}\`${evidence.note === undefined ? '' : ` · ${escapeInline(evidence.note)}`}`)
  }
  lines.push('', '## Usage', '',
    `- Injected/read count: ${record.useCount}`,
    `- Helpful feedback: ${record.positiveFeedback}`,
    `- Negative feedback: ${record.negativeFeedback}`,
    ...(record.lastUsedAt === undefined ? [] : [`- Last used: ${formatTime(record.lastUsedAt)}`]),
    '', '## Revision history', '')
  for (const revision of revisions) {
    lines.push(`- r${revision.revision} · ${revision.operation} · ${formatTime(revision.createdAt)} · ${escapeInline(revision.actor.kind)}:${escapeInline(revision.actor.id)} · \`${revision.contentHash.slice(0, 12)}\``)
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderCandidates(candidates: readonly MemoryCandidate[]): string {
  const lines = [
    '# Candidate review queue',
    '',
    '> Generated by dsh-memory. Candidate text is untrusted and has not been published.',
    '',
  ]
  if (candidates.length === 0) lines.push('No pending candidates.', '')
  for (const candidate of candidates) {
    lines.push(
      `## ${escapeInline(candidate.content.subject)}`,
      '',
      `- Candidate: \`${escapeCode(candidate.id)}\``,
      `- Operation: ${candidate.operation}`,
      `- Scope: ${escapeInline(candidate.content.scope.type)} · \`${escapeCode(candidate.content.scope.key)}\``,
      `- Kind: ${candidate.content.kind}`,
      `- Proposed by: ${escapeInline(candidate.actor.kind)}:${escapeInline(candidate.actor.id)}`,
      `- Proposed: ${formatTime(candidate.createdAt)}`,
      ...(candidate.targetMemoryId === undefined ? [] : [`- Target: \`${candidate.targetMemoryId}\` @ r${candidate.expectedRevision}`]),
      '',
      '**When**', '', htmlPre(candidate.content.applicability), '',
      '**What**', '', htmlPre(candidate.content.action), '',
      '**Why**', '', htmlPre(candidate.content.rationale), '',
    )
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function renderConflicts(conflicts: readonly MemoryConflict[], records: readonly MemoryRecord[]): string {
  const byId = new Map(records.map(record => [record.memoryId, record]))
  const lines = [
    '# Open conflicts',
    '',
    '> Generated by dsh-memory. Both sides remain unavailable to normal retrieval until a reviewer resolves the conflict.',
    '',
  ]
  if (conflicts.length === 0) lines.push('No open conflicts.', '')
  for (const conflict of conflicts) {
    const left = byId.get(conflict.leftMemoryId)
    const right = byId.get(conflict.rightMemoryId)
    lines.push(
      `## Conflict \`${escapeCode(conflict.id)}\``,
      '',
      `- Created: ${formatTime(conflict.createdAt)}`,
      `- Left: [${escapeInline(left?.subject ?? conflict.leftMemoryId)}](../records/${safeFileName(conflict.leftMemoryId)}.md) @ r${conflict.leftRevision}`,
      `- Right: [${escapeInline(right?.subject ?? conflict.rightMemoryId)}](../records/${safeFileName(conflict.rightMemoryId)}.md) @ r${conflict.rightRevision}`,
      '',
    )
  }
  return `${lines.join('\n').trimEnd()}\n`
}

function atomicWrite(path: string, content: string): void {
  const parent = dirname(path)
  mkdirSync(parent, { recursive: true, mode: 0o700 })
  const temporary = join(parent, `.${basename(path)}.${randomUUID()}.tmp`)
  const fd = openSync(temporary, 'wx', 0o600)
  try {
    writeFileSync(fd, content, { encoding: 'utf8' })
    fsyncSync(fd)
  } finally {
    closeSync(fd)
  }
  try {
    renameSync(temporary, path)
  } catch (error) {
    try {
      unlinkSync(temporary)
    } catch {
      // Preserve the publication error.
    }
    throw error
  }
}

function readManifest(root: string): readonly string[] {
  const path = join(root, MANIFEST)
  if (!existsSync(path)) return []
  try {
    const value: unknown = JSON.parse(readFileSync(path, 'utf8'))
    if (!Array.isArray(value) || value.some(item => typeof item !== 'string' || !isSafeRelative(item))) return []
    return value
  } catch {
    return []
  }
}

function removeGeneratedFile(root: string, relative: string): void {
  if (!isSafeRelative(relative)) return
  const path = join(root, relative)
  try {
    const stat = lstatSync(path)
    if (stat.isSymbolicLink() || !stat.isFile()) return
    unlinkSync(path)
  } catch {
    // A missing derived page needs no recovery.
  }
}

function isSafeRelative(value: string): boolean {
  return /^(?:README\.md|records\/[A-Za-z0-9._-]+\.md|review\/(?:candidates|conflicts)\.md)$/.test(value)
}

function safeFileName(value: string): string {
  return value.replace(/[^A-Za-z0-9._-]/g, '_')
}

function htmlPre(value: string): string {
  return `<pre>${escapeHtml(value)}</pre>`
}

function escapeHtml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function escapeInline(value: string): string {
  return escapeHtml(value.replace(/[\r\n]+/g, ' ').replace(/([\\`*_[\]<>#])/g, '\\$1'))
}

function escapeCode(value: string): string {
  return value.replace(/`/g, '\\`').replace(/[\r\n]+/g, ' ')
}

function formatTime(value: number): string {
  return new Date(value).toISOString()
}
